### ISSUE TITLE
Error: cannot find Read_Gebiedsindelingen_gpkg/provincie_gegeneraliseerd

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/Ruimtelijke_Restricties#1]
In item:
/SourceData/RegioIndelingen/Read_Gebiedsindelingen_gpkg

ontbreekt
provincie_gegeneraliseerd

daardoor is /Restricties/Generate_all niet te runnen
![image](https://github.com/user-attachments/assets/e9972e68-c8ae-4e34-b63f-75bbde7cd80d)

**Comment by basvanbemmel** [comment]
IK zie dat er een nieuwe SD is maar ook dan krijg ik een foutmelding

![image](https://github.com/user-attachments/assets/3597c9e6-b6d4-4573-a41a-36d5cbc31438)

**Comment by jipclaassens** [comment]
Welke instellingen gebruik je? Ik heb die pmv nog niet nodig gehad..

**Comment by jipclaassens** [comment]
Nvm, gevonden.

**Comment by jipclaassens** [comment]
Ik had op een tweede computer nog niet alles uit de SD gecommit. Nu wel! Excuus.
